# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(blank=True, null=True)),
                ('set_name', models.CharField(blank=True, db_column='setName', max_length=60, null=True)),
                ('short_description', models.CharField(blank=True, db_column='shortDescription', max_length=45, null=True)),
                ('long_description', models.CharField(blank=True, db_column='longDescription', max_length=240, null=True)),
                ('value', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(db_column='homeworkID', primary_key=True, serialize=False)),
                ('set_date', models.DateField(db_column='setDate')),
                ('due_date', models.DateField(db_column='dueDate')),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.IntegerField()),
                ('type', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'homework',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(blank=True, db_column='addedBy', null=True)),
            ],
            options={
                'db_table': 'homework_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('original_name', models.CharField(db_column='originalName', max_length=100)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'homework_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'homework_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'homework_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, db_column='submittedDate', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewedDate', null=True)),
            ],
            options={
                'db_table': 'homework_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OneNoteLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('schoolbag_id', models.IntegerField(db_column='schoolbagId')),
                ('url', models.CharField(blank=True, max_length=600, null=True)),
                ('onenote_id', models.CharField(blank=True, db_column='oneNoteId', max_length=100, null=True)),
                ('content', models.TextField(blank=True, db_column='pageContent', null=True)),
                ('table', models.CharField(blank=True, db_column='schoolbagTable', max_length=15, null=True)),
                ('client_url', models.CharField(blank=True, db_column='clientUrl', max_length=600, null=True)),
            ],
            options={
                'db_table': 'one_note_links',
                'managed': False,
            },
        ),
    ]
