# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('class_id', models.AutoField(db_column='classID', primary_key=True, serialize=False)),
                ('extra_ref', models.CharField(db_column='extraRef', max_length=10)),
                ('resource_id', models.CharField(blank=True, db_column='resourceId', max_length=60, null=True)),
                ('external_id', models.CharField(blank=True, db_column='externalId', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'managed': False,
                'verbose_name_plural': 'Classes',
                'db_table': 'classlist',
            },
        ),
        migrations.CreateModel(
            name='ClassListOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'classlistofusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(db_column='Day')),
                ('room', models.CharField(db_column='Room', max_length=10)),
                ('external_id', models.CharField(blank=True, db_column='externalId', max_length=100, null=True)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='subject', max_length=72)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(db_column='areaId')),
                ('school_id', models.IntegerField(db_column='schoolId')),
            ],
            options={
                'db_table': 'subject_areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectsDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'subjects_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeachersTeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'teachersteach',
                'managed': False,
            },
        ),
    ]
